apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xsjclgck6-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/xsjclgck6-java-springboot-gitops